name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag centos-build:latest
    - name: Docker container run
      run: docker run -td -p 33:22 centos-build:latest
    - name: Connection 33 port
      run: echo quit | telnet localhost 33 2>/dev/null | grep Connected
